name: latlong
description: Lightweight library for common latitude and longitude calculation
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-latlong

version: 0.5.3

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  logging: '>=0.11.3 <1.0.0'
  console_log_handler: '>=1.1.0 <2.0.0'
    # git: git@github.com:MikeMitterer/dart-console_log_handler.git
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  validate: ^1.0.0

  intl: '>=0.15.0 <1.0.0'

dev_dependencies:
  test: any

  build_runner: any
  build_test: any
  build_web_compilers: any
