name: latlong
description: Lightweight library for common latitude and longitude calculation
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-latlong

version: 0.2.1

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  browser: ^0.10.0

  logging: ^0.11.0
  logging_handlers: ^0.8.0
  console_log_handler: ^0.1.0

  validate: ^1.0.0

dev_dependencies:
  test: any
  grinder: any